### ISSUE TITLE
Does Not Show Whitespace Between Words

### ISSUE THREAD

**Issue by bobrocke** [atom/whitespace#50] opened 2014-11-22 15:55 UTC
Only leading and trailing whitespace is shown. Spaces within a line of text or code are not shown.

Is this expected?

Is there a way to enable that ability?

**Comment by lee-dohm** [comment] 2015-06-30 14:04
Closing this as duplicate of atom/atom#6824.

**Closed by lee-dohm** 2015-06-30 14:04 UTC
