### ISSUE TITLE
Select "Keep Markdown Line Break Whitespace", but whitespace is removed for md file

### ISSUE THREAD

**Issue by zhangjianye** [atom/whitespace#137] opened 2016-11-18 08:39 UTC

**Comment by joallard** [comment] 2016-12-05 22:51
Severity: major. Can't save files with any forced linebreaks.

**Comment by 50Wliu** [comment] 2016-12-21 16:20
Can everyone affected by this issue please answer the following questions:
* Is this issue reproducible in safe mode (`atom --safe`)?
* If so, what version of Atom are you using?  Use the `atom --version` command and copy/paste the **entire** output.
* What OS are you running?
* Does this issue affect just a single Markdown file or all Markdown files?

Thanks!

**Comment by joallard** [comment] 2016-12-21 16:49
```
atom-ws-137$ touch file.md
atom-ws-137$ atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
atom-ws-137$ atom --safe .
atom-ws-137$ # pkg lang markdown is disabled in safe, syntax not recognized
```

OS X 10.11

1. Start Atom with `atom --safe .`
2. Open `file.md`
3. Insert the following in file. (Note: two spaces are at the end of the second line)

```
first line  
second line
```

4. Save

Actual: Spaces are removed from Line 1

**Comment by joallard** [comment] 2016-12-21 16:53
Bonus gif:
![](http://g.recordit.co/dEYaSlQoxb.gif)

**Comment by TheIdealis** [comment] 2017-01-07 09:38
Have you enabled the `language-gfm` package in safe-mode? It will be disabled by most of the other markdown packages isn't enable by default in safe mode. It seems to me, that the `keepMarkdownLineBreakWhitespace` option only applies to the `gmf.source` scope, but not to the `text.md` scope.  
I could circumvent this problem, by adding

    ".text.md":  
      whitespace:  
        removeTrailingWhitespace: false

to my config.cson.

**Comment by TheIdealis** [comment] 2017-01-07 09:48
I think, one could simply add the `text.md` scope to this lines from `lib/whitespace.js`

    const keepMarkdownLineBreakWhitespace =
      grammarScopeName === 'source.gfm' &&
      atom.config.get('whitespace.keepMarkdownLineBreakWhitespace')

**Comment by Xeboc** [comment] 2017-01-23 23:12
Reproduced with `atom --safe`

james@james:~$ atom --version
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Running on Ubuntu 16.10

Affects all .md files for me.  This has been working well until updates within the last few days.

**Comment by simonmcl** [comment] 2017-01-26 11:28
I've been using Atom on / off for a few years. Started using it again recently and came across this issue. This definitely did not always happen, as I was promoting Atom as a markdown editor internally.

This has become very frustrating for us as we use markdown for some project documentation.

Version:
```
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

OS:
Mac OSX: 10.12.3

Affecting all `.md` files across all projects.

**Comment by 50Wliu** [comment] 2017-01-26 19:33
So it looks like this is happening for people who have the language-gfm package disabled?  @simonmcl can you reproduce this in safe mode (`atom --safe`) and make sure that the `language-gfm` package is enabled?

**Comment by lee-dohm** [comment] 2017-05-23 15:53
This appears to be caused by using a package with a different scope for Markdown files. Since everything seems to be working properly with a standard configuration of Atom, I'm going to close this. If anyone would like to work on a solution that works for all types of Markdown files, we would be open to reviewing a well-crafted PR.

**Closed by lee-dohm** 2017-05-23 15:53 UTC
Labels: help-wanted

**Comment by emlai** [comment] 2017-07-17 14:06
For people having this problem:

Check that your project doesn't have an `.editorconfig` file with `trim_trailing_whitespace = true` set for all files. This just happened to me and it took a while to figure out.
