### ISSUE TITLE
Whitespace stripped from markdown despite settings

### ISSUE THREAD

**Issue by amygroshek** [atom/whitespace#167] opened 2017-11-16 17:57 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whitespace is being stripped from .md files despite the plugin "Keep markdown line break whitespace" option being selected. I also tried to override by blacklisting .md files in config.cson, to no effect:

```
  whitespace:
    fileBlacklist: [
      "*.md"
    ]
    scopeBlacklist: [
      ".source.gfm"
    ]
```
And tried in various ways to set the setting in config.cson:

```
"*":
  "":
    gfm:
      source:
        whitespace:
          removeTrailingWhitespace: false
    source:
      gfm:
        editor:
          removeTrailingWhitespace: false
    text:
      md:
        whitespace:
          removeTrailingWhitespace: false
```

### Steps to Reproduce

1. Install plugin/verify that plugin is enabled
2. In plugin settings, make sure that the "Keep Markdown Line Break Whitespace" option is checked
3. Open an .md file and add two-space line breaks to some lines
4. Save the file

**Expected behavior:** Whitespace is not removed

**Actual behavior:** Whitespace is removed

**Reproduces how often:** Every time I save a file

### Versions

macpro@~ $: atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
macpro@~ $: apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.5.4

### Additional Information

Sorry, I know there are a lot of markdown issues in this repo, but this is driving me nuts. Screenshot shows my settings and the two file format blacklist settings reflected from the config file.

![screen shot 2017-11-16 at 11 49 37 am](https://user-images.githubusercontent.com/746182/32907359-5db89274-cac5-11e7-9bed-97db25fd3af9.png)

**Comment by foreshadow** [comment] 2017-12-14 07:06
Same. It should have been set by default that keep markdown line break white spaces, but still stripped my `.md` files.

**Comment by dmcnamee** [comment] 2017-12-29 00:15
Same issue occurring for me.

~ atom --version
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

~ apm --version
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.13
git 2.14.3

**Comment by cniklas** [comment] 2018-01-20 11:07
Same with me.
I know this feature used to work a few month ago and just recently detected by accident that the plugin strips line breaks in my markdown files, despite the settings.

**Comment by Ben3eeE** [comment] 2018-01-22 14:41
Do you have the `language-markdown` package installed? /cc: https://github.com/burodepeper/language-markdown/issues/200

**Comment by amygroshek** [comment] 2018-01-22 14:59
^Yes.

**Comment by Ben3eeE** [comment] 2018-01-22 15:19
@amygroshek Thank you for reporting back :bowing_man: 

Since this issue happens because you have the `language-markdown` package installed I am going to close this as a duplicate of https://github.com/atom/whitespace/issues/137

You may want to ask over at https://github.com/burodepeper/language-markdown/issues/200 or check the following FAQ entry on their repo to get further assistance on how to configure `language-markdown` to work with the `whitespace` package /cc: https://github.com/burodepeper/language-markdown/blob/master/FAQ.md#trailing-whitespace-is-automatically-removed-but-i-dont-want-that

From a quick glance it seems like the syntax in the FAQ is slightly different from what you posted in the body of this issue.

---

We noticed that this is a duplicate of https://github.com/atom/whitespace/issues/137. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-01-22 15:19 UTC
Labels: duplicate

**Comment by amygroshek** [comment] 2018-01-22 15:22
It still happens when I disable language-markdown.

**Comment by Ben3eeE** [comment] 2018-01-23 07:07
This is because whitespace uses the language grammar from the opened file to determine if it is a markdown file or not. It currently does this with the grammar that language-gfm sets on the file. language-markdown disables language-gfm by default so no markdown package would be enabled if you just disable language-markdown.

You would need to disable language-markdown, enable language-gfm and reopen any open markdown files (or restart Atom).

**Comment by amygroshek** [comment] 2018-01-23 18:58
That's very helpful @Ben3eeE . Thanks.
