### ISSUE TITLE
Feature request: remove whitespace only on lines that are edited.

### ISSUE THREAD

**Issue by jcalfee** [atom/whitespace#90] opened 2015-08-24 13:40 UTC
It would be nice to remove tailing white spaces on just the lines that are touched?  I work on a project where git diffs are important.  I can't allow whitespace to mangle any other code it makes the diffs too hard to read.  It would be less opinionated of the software if only touched lines were clean of erroneous whitespace but the rest of the code base was alone.

If you had a way to clean all whitespace all at once so it could be made in a single commit that would be reasonable feature too.  However, the more pressing issue is to limit the scope of the changes to keep diffs reasonable.

I'm new here, I'm glad my first change was only a single line.  If I had made more extensive changes across many files this would have been a unwelcome surprise.

**Comment by matz3** [comment] 2015-08-24 13:50
Seems to be a duplicate of #8

**Comment by mnquintana** [comment] 2015-08-24 13:59
Thanks @matz3! This does indeed look like a duplicate of #8 - closing this out in favor of that issue.

**Closed by mnquintana** 2015-08-24 13:59 UTC
