### ISSUE TITLE
Package deletes trailing whitespace when Enter/Return is pressed in a line that has only whitespace before the cursor

### ISSUE THREAD

**Issue by WalterGR** [atom/whitespace#106] opened 2016-01-06 10:42 UTC
Atom 1.3.2 on OS X 10.10.5.

Repro:

1.  Ensure `whitespace` package is enabled.
2.  Create new file.
3.  Press Space several times.
4.  Press Enter/Return.

Expected:

Those spaces aren't deleted immediately.  Rather, the package "Strips trailing whitespace and adds a trailing newline when an editor is saved." as per its description.

Actual:

The spaces are deleted immediately.

**Comment by lee-dohm** [comment] 2016-01-13 05:25
Confirmed on Atom v1.3.3 on Mac OS X 10.11.2.

**Comment by WalterGR** [comment] 2016-01-14 03:17
Are you sure this is an enhancement?

The behavior of the package and the description can't both be correct, since they differ.  Either the behavior or the description are wrong.

Whenever a program changes what a user enters behind their back, there needs to be a solid justification for it.  What's the justification for doing this before save, since this package will do it upon saving?  What does the current behavior earn the user?

I see no benefit and only a cost: it interferes with what I'm doing.  Now I have to go out of my way when I'm formatting things to *avoid* pressing Enter after only whitespace, since Atom is 'finicky about whitespace.'  What's the benefit of having to include that in my mental model of Atom?

**Comment by lee-dohm** [comment] 2016-01-14 03:21
Turns out, this is a duplicate of https://github.com/atom/whitespace/issues/93 which is being addressed in #94.

**Closed by lee-dohm** 2016-01-14 03:21 UTC
Labels: duplicate

**Comment by WalterGR** [comment] 2016-01-14 03:28
Thanks for the links.
