### ISSUE TITLE
Trailing whitespaces stripped in .jade files 

### ISSUE THREAD

**Issue by ChrisCinelli** [atom/whitespace#131] opened 2016-08-27 01:14 UTC
The note at the bottom of the plugin says: "Note: for .source.jade removing trailing whitespace is disabled by default." But it is not the case for me.

I even tried to add : 

```
'.jade.text':
  whitespace:
    removeTrailingWhitespace: false
```

But it still keep stripping them

**Comment by lee-dohm** [comment] 2016-08-27 04:20
If the scope of your Jade files is `.jade.text` then that would be the explanation. It states "for `.source.jade` removing trailing whitespace is disabled by default." This mentions nothing about `.jade.text`.

As to why it isn't working when you specify `.jade.text`, do you have a set of repro steps that I can follow to try and reproduce the problem? Preferably including the name of the Jade package you have installed since I don't use Jade.

**Comment by Ben3eeE** [comment] 2016-12-19 11:45
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/whitespace/issues/131#issuecomment-242894930. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2016-12-19 11:45 UTC
Labels: more-information-needed
