### ISSUE TITLE
"Remove Trailing Whitespace" should not be on by default for Plain text files

### ISSUE THREAD

**Issue by paulciorogar** [atom/whitespace#173] opened 2018-01-23 16:26 UTC
As the title says I think plain text files should not be subject of removing trailing whitespace. I spent 2 days trying to figure out why my newly created uuencode and uudecode script was working in my tests but when trying to decode a real file would fail. The files were plain text I opened them in Atom remove some metadata then saved them so I can decode them with my little tool and it didn't work. Space is used as a padding byte in this format. I understand the option of removing space from code but not plain text files.

**Comment by Baelyk** [comment] 2018-03-17 15:34
I don't have a problem with it being on by default, but it would be nice if there was a way to disable it on a file-by-file or at least project-by-project level (ideally without having to add a .atom-whitespace file or a comment in the file).

There have been a couple of time where some files I am working have some weird formatting but need that, and then I have to go and turn off whitespace to save it, then turn it back on.

**Comment by thomasjo** [comment] 2018-03-20 05:55
Closing as duplicate of #10.

**Closed by thomasjo** 2018-03-20 05:55 UTC
